### PR TITLE
Fix key= warnings, and allow passing through <Text> props

### PR DESCRIPTION
**Pull request by mikelambert**
This latter change would be an easier way of doing numberOfLines stuff. (Or alternatively, passing through all unknown props to <Text>.)

I have a change to RN's <Text> (hoping to push upstream at some point) to support a new property selectable={true}, and would like to pass that through <Autolink> too.

### CODE REVIEW

**Comment by mikelambert** [comment]
This latter change would be an easier way of doing numberOfLines stuff. (Or alternatively, passing through all unknown props to <Text>.)

I have a change to RN's <Text> (hoping to push upstream at some point) to support a new property selectable={true}, and would like to pass that through <Autolink> too.

**Comment by joshswan** [comment]
Any chance you could split this into two PRs? The `key` fix looks good to go, but I think a better way of doing the text props would be to just pass through all unknown props as you mentioned above (and remove the `numberOfLines` that I put in before). Thoughts?

**Comment by mikelambert** [comment]
I'm fine with that, it'll just mean relaxing some of your prop typechecks, I think? Let me pull the first fix into a new branch and send a pull request.

**Comment by mikelambert** [comment]
See https://github.com/joshswan/react-native-autolink/pull/6

**Comment by joshswan** [comment]
Alrighty, #6 is merged and released in 0.4.1.

With regards to the Text props, I think we can do it pretty easily by just [destructuring](https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx) `this.props` and then passing `...other` (the remaining props) to the `Text` component. That or looping through the props, checking if each is "unknown", and adding to an `other` object. Ideally I'd like to avoid relaxing the `PropTypes` checks as they can be pretty useful when you're unsure of how to use the prop/component.

**Comment by mikelambert** [comment]
Agreed on the destructuring. I actually had a change to do that...it's just
a lot of destructuring vars in the render() function to get the otherProps.
:)

2016年6月9日(木) 16:47 Josh Swan <notifications@github.com>:

**Comment by joshswan** [comment]
True. The other vars can replace the `this.props` references on lines `83-88` so maybe it won't be too bad

**Comment by joshswan** [comment]
Props are passed through to the Text node with v0.6.0

**Pull request closed without merging**
